name = "Badds"
author = "badd"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83a8c066de71cc46d01c854afa86223563e2adb05d099c794ac089790ed04e10"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
