name = "Badds"
author = "badd"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5678b53182d236619dcee7ef420d3391dc9780e40e385dfeedc509792aacff07"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
