name = "Badds"
author = "badd"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d61278bef213171568734671bb0b2eabc87c47d12874aca15a695fa0c07b024"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
